[package]
name = "winr-inject"
version.workspace = true
edition.workspace = true

[lib]
name = "winr_inject"
path = "src/lib.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tracing.workspace = true
windows.workspace = true
winr-perception = { path = "../winr-perception" }
winr-workflows = { path = "../winr-workflows" }
winr-types = { path = "../winr-types" }
